# Generated by Django 3.0.4 on 2020-05-14 12:44

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HighSchool',
            fields=[
                ('school_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('school_address', models.CharField(max_length=200)),
                ('school_contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('school_mail', models.EmailField(max_length=254)),
                ('school_image', models.ImageField(default='defaultLogo.png', upload_to='images/')),
                ('responsible_person_first_name', models.CharField(max_length=200)),
                ('responsible_person_last_name', models.CharField(max_length=200)),
                ('responsible_person_mail', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HighSchoolAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=100)),
                ('admin_password', models.CharField(max_length=32)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='high_school_app.HighSchool')),
            ],
        ),
    ]
