# Generated by Django 3.0.4 on 2020-05-14 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('high_school_app', '__first__'),
        ('university_app', '0006_delete_guide'),
        ('individual_app', '0002_auto_20200506_2216'),
        ('guide_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualAppointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('faculties', models.TextField()),
                ('appointment_date_start', models.DateTimeField()),
                ('appointment_date_end', models.DateTimeField()),
                ('capacity', models.IntegerField()),
                ('isVisible', models.BooleanField(default=False)),
                ('guide', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guide_app.Guide')),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='individual_app.Individual')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_app.University')),
            ],
        ),
        migrations.CreateModel(
            name='HighSchoolAppointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('faculties', models.TextField()),
                ('appointment_date_start', models.DateTimeField()),
                ('appointment_date_end', models.DateTimeField()),
                ('capacity', models.IntegerField()),
                ('isVisible', models.BooleanField(default=False)),
                ('guide', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guide_app.Guide')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='high_school_app.HighSchool')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_app.University')),
            ],
        ),
    ]
