# Generated by Django 3.0.5 on 2020-05-14 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('high_school_app', '0001_initial'),
        ('university_app', '0006_delete_guide'),
        ('individual_app', '0002_auto_20200506_2216'),
        ('appointment_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highschoolappointment',
            name='isVisible',
        ),
        migrations.RemoveField(
            model_name='individualappointment',
            name='isVisible',
        ),
        migrations.CreateModel(
            name='IndividualAppointmentRequest',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('faculties', models.TextField()),
                ('appointment_date_start', models.DateTimeField()),
                ('appointment_date_end', models.DateTimeField()),
                ('capacity', models.IntegerField()),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='individual_app.Individual')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_app.University')),
            ],
        ),
        migrations.CreateModel(
            name='HighSchoolAppointmentRequest',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('faculties', models.TextField()),
                ('appointment_date_start', models.DateTimeField()),
                ('appointment_date_end', models.DateTimeField()),
                ('capacity', models.IntegerField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='high_school_app.HighSchool')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_app.University')),
            ],
        ),
    ]
