# Generated by Django 3.0.5 on 2020-05-24 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0002_auto_20200514_1404'),
        ('appointment_app', '0002_auto_20200514_1757'),
    ]

    operations = [
    ]
