# Generated by Django 3.0.4 on 2020-05-14 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university_app', '0006_delete_guide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('guide_id', models.AutoField(default=11, primary_key=True, serialize=False)),
                ('guide_name', models.CharField(max_length=100)),
                ('guide_faculty', models.CharField(max_length=100)),
                ('university_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_app.University')),
            ],
        ),
        migrations.CreateModel(
            name='GuideRequest',
            fields=[
                ('guide_id', models.AutoField(primary_key=True, serialize=False)),
                ('guide_name', models.CharField(max_length=100)),
                ('guide_faculty', models.CharField(max_length=100)),
                ('university_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_app.University')),
            ],
        ),
        migrations.CreateModel(
            name='GuideCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_username', models.CharField(max_length=100)),
                ('guide_password', models.CharField(max_length=32)),
                ('guide_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide_app.Guide')),
            ],
        ),
    ]
