# Generated by Django 3.0.4 on 2020-04-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityschedule',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
