# Generated by Django 3.0.4 on 2020-04-16 20:03

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0002_universityschedule_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='university_contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
