# Generated by Django 3.0.4 on 2020-04-23 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0003_auto_20200416_2303'),
        ('university_app', '0003_auto_20200409_1018'),
        ('university_app', '0003_auto_20200415_1900'),
    ]

    operations = [
    ]
