# Generated by Django 3.0.4 on 2020-04-23 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0004_merge_20200423_0815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guide',
            old_name='universiy',
            new_name='university_name',
        ),
        migrations.RenameField(
            model_name='universityadmin',
            old_name='universiy',
            new_name='university_name',
        ),
        migrations.RenameField(
            model_name='universityschedule',
            old_name='university',
            new_name='university_name',
        ),
    ]
