# Generated by Django 3.0.4 on 2020-05-06 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0005_auto_20200423_0815'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guide',
        ),
    ]
