# Generated by Django 3.0.4 on 2020-04-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityRequest',
            fields=[
                ('university_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('university_address', models.CharField(max_length=200)),
                ('university_contact_number', models.IntegerField()),
                ('university_mail', models.EmailField(max_length=254)),
                ('university_faculties', models.CharField(max_length=500)),
            ],
        ),
    ]
