# Generated by Django 3.0.4 on 2020-04-03 09:05

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('website_admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityrequest',
            name='university_contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
