# Generated by Django 3.0.4 on 2020-04-23 08:15

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('website_admin_app', '0002_auto_20200403_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighSchoolRequest',
            fields=[
                ('school_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('school_address', models.CharField(max_length=200)),
                ('school_contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('school_mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
