# Generated by Django 3.0.5 on 2020-04-27 19:50

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('website_admin_app', '0003_highschoolrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualRequest',
            fields=[
                ('individual_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('individual_contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('individual_mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
